apiVersion: v1
kind: Ingress
metadata: 
  name: ingress-wear-watch
spec:
  rules:
  - host: wear.my-online-store.com
  - http:
      paths:
      - path: /wear
        backend: 
          service:
            name: wear-service
            port: 80
      - host: watch.my-online-store.com
      - path: /watch
        backend: 
          service:
            name: watch-service
            port: 80