apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sidecar-container
    image: busybox
    command: ["sh", "-c", "echo Hello from the sidecar container! && sleep 3600"]

    # kubectl apply -f pod-example.yml (kubectl create -f pod-example.yml requires --save-config flag to be used)
    # kubectl get pods
    # kubectl describe pod nginx-pod