apiVersion: v1
kind: Pod
metadata:  # can only have fields that are allowed in the metadata section of a pod, such as name and labels
  name: myapp-pod
  labels:  # can have any fields
      app: myapp
      type: front-end
spec:
  containers:  # can have multiple containers in a pod, but for this example we will only have one container
  - name: myapp-container
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80

# kubectl create -f pod-definition.yml
# kubectl get pods
# kubectl describe pod myapp-pod  