apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: LoadBalancer  # could also be NodePort or ClusterIP. Default is ClusterIP. LoadBalancer is only available in cloud providers like AWS, GCP, Azure, etc. It will create a cloud load balancer and assign an external IP address to it.
  ports:
    - port: 80    # (Cluster Internal): The port exposed inside the cluster. Other pods inside the cluster use this port to talk to this service.
                  # Only required field                                                                                        
      targetPort: 80 # (Pod Internal): The actual port your Nginx container is listening on inside the pod. The service forwards traffic from port to targetPort 
                  # If not specified, defaults to the value of port
      nodePort: 30008  # (External Access): The port opened on every Kubernetes cluster node's external IP address. Use this in your browser for example. 
                       # If not specified, Kubernetes will automatically assign a port in the range 30000-32767

# kubectl create -f loadbalancer-service-definition.yml
# kubectl get services        