apiVersion: v1
kind: Pod
metadata: 
  name: my-custom-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --config=/etc/kubernetes/config/my-scheduler.yaml
    image: k8s.gcr.io/kube-scheduler:v1.20.0
    name: kube-scheduler