apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  priorityClassName: high-priority
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 8080