apiVersion: certificates.k8s.io/v
kind: CertificateSigningRequest
metadata:
  name: adam-csr
spec:
  signerName: Kubernetes.io/kube-apiserver-client
  expirationSeconds: 600
  usages:
  - client auth
  request: 
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5N
QXNHQTFVRUF3d0VZV1JoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0Nn
Z0VCQU1MRnd2YUE0N1FsUmlhZWlxUTg0MEFyMkpQamJZTkZidkhJMHJnVW5YNDZrZDJECmFXNkZ5
eS9xNk9WQWFVdWhMcG9zaXZWQmlMZEN2ZHYwUDhMK1BqUGk4b0Y2RkJIdDdHWVM1WTRBejR1Nzha
QWMKVGNFbGYwaGNLNDhOSUJDV1JOUXQzMC9Vb056T2JLR21GbVFvU0F0WDJrajBQbWNCWE9qQ1FP
bHNjeDM1dVB0dQpoWlUwUzFyeXFqYnhkTmNPeVdIVmZvSU12eDFNYlkyaVF5NVQwa2lOdXZONENi
ejZVQjNxNnRmNGtOK2FMV3RTClc1REVFYTAvM0lLU29WdDdqWk91ZlR4KzFYOEl0TzlRSTNPdlR4
S3JHTHRkd3MzYjdGV0Fsc3kwakFZVTRaeUoKUUtUZkpOYUtHS2d2bmVmT1dsV1BGNjNRZkd5dFVG
Si9tRVl6T2djQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQWJmVmI5OVRHU21i
QkI5NS9yOHFGckZlQ25Mb29FbElGeGlOWHFyMlJNL0xWQ0JQU0hmaFRrCmJZVlVrS1V5S0p1VXJM
aU1wVm5uK0VhTE1hemVMVFJKejJDNDRORzlGZzdnTXVVYVE4cnBtTVZtN1gyZ3RCUjYKY29DcHdi
RklqOEhXSXdGWjUrd3dZby9rUU9DUVVNM2Q3S0hHMUx6aXBGMzJVYmdiMWtMek10elRUd0ZndTNS
ZApMYXYxWWZUbGk5cWZ2UHR1Q3VOajVmeEI1emhtdlJ6ZTIyZ0hmRU1vTEk4K21DRlFOaXJqODdD
NGw2dGFqVHZwCmtOQ01JS0RUZFV1R3FjRkc3aEdmU096YWpwbFVZc3haTmJmcXVFRmxLNFBUNE1J
WVRLZ2NIUXJCR0hPM0dzN24KbjhxR3YzZjlWVVBsY3ZRNCsrVzAzRjNMRk5UV2hDdkoKLS0tLS1F
TkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  conditions:
  - type: Approved
    status: "True"
    reason: KubectlApprove
    message: "This CSR was approved by kubectl certificate approval"
