apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu:latest       # docker run ubuntu:latest sh -c "sleep 10"
    command: ["sh", "-c"]   # analogous to the ENTRYPOINT in Docker
    args: ["sleep 10"]               # analogous to the CMD in Docker