apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ca.crt # self-signed
    server: htts://kube-api-server:6443
  name: kubernetes
kind: Config
users:
- name: kubernetes-admin
user:
    client-certificate-data: admin.crt
    client-key-data: admin.key